gun1=int(input("1. gün okunan sayfa: "))
gun2=int(input("2. gün okunan sayfa: "))
gun3=int(input("3. gün okunan sayfa: "))
gun4=int(input("4. gün okunan sayfa: "))
gun5=int(input("5. gün okunan sayfa: "))
gun6=int(input("6. gün okunan sayfa: "))
gun7=int(input("7. gün okunan sayfa: "))
toplam=(gun1+gun2+gun3+gun4+gun5+gun6+gun7)
print("1 haftalık okunan sayfa: ",toplam)